---
title: "Project Description Outline"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Names of group members

Person 1 = Simone Famiano, 
Person 2 = John Hios, 
Person 3 = Grant Walker, 
Person 4 = Jack Patton

### Roles & responsibilities of each member

**Person 1** worked on ...

**Person 2** worked on ...

Person 3, Grant Walker, worked on:

Identified geospatial mapping within leaflet as the Extension to the geographic variation MVP. Located shapefiles for the NHS Health Board regions and loaded them into QGIS software to  

**Person 4**

**Everyone** worked on ...

### Brief description of dashboard topic

Our dashboard contains ...

Our topic is ...

Person 3 - How significant are the differences in hospital activity across the country? Does urban/rural have an impact or is it related to the size and capacity of the health board?

The dashboard outlines our topic in terms of ...

### Stages of the project

* Planning & dashboard wireframe

On day 1 of the group project we held a meeting to plan the approach to creating the dashboard. During this meeting we identified key miletones in the project and a work programme. We discussed questions of interest from the examples list provided and then identified that each team member would answer one of these on a seperate tab. This approach would allow for discrete workflows within a cohesive story.

* Git branching & version control

* Choosing datasets

Each group member looked for the datasets which best answered their questions.

and so on ...

### Which tools were used in the project

* Zoom (daily stand-ups and occasional mob programming)

We held morning stand-ups in person and, on non-business days, via Zoom.  We used Trello as a project planning tool. We input the programme dates into the Trello page and attached task descriptions along with minutes from the project planning meeting.

* Trello (planning & task allocation)

* Git/GitHub (collaboration & version control)

Each team member had a seperate branch in addition to the main branch. We pushed our working code to our respective branches. To compile all the tabs into one app we pushed Person 1's code to main and then brought it down into Person 2's branch to undertake the merge. Once the code had been merged and worked into was pushed back to the main branch. This process was repeated for Person 3 and Person 4.

and so on ...

### How did you gather and synthesise requirements for the project?

We synthesised the information given in the brief by ...

We prioritised ...

### Motivations for using the data you have chosen

We used the dataset on ... to answer ... and because it was ...

### Data quality and potential bias, including a brief summary of data cleaning and transformations

According to the About tab on the dataset page/dedicated page online, the data quality ...

The dataset may/may not be biased because ...

To clean the datasets we ...

Person 3 - selected columns of interest, removed values which were not required in the specific analyses output.

### How is the data stored and structured

[**Hint**: This page offers a good starting point for understanding the data structure: https://guides.statistics.gov.scot/article/34-understanding-the-data-structure]

The data is in the form of ...

This means ...

Benefits of storing the data like this are ...

### Ethical and legal considerations of the data

[**Hint:** this page contains information on the Open Government License which covers most datasets on statistics.gov.scot: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/]

There are no/There may be ethical considerations, because ...

The datasets are covered by the Open Government License, which means ...